-- AlterTable
ALTER TABLE "Resource" ALTER COLUMN "tags" DROP DEFAULT,
ALTER COLUMN "fileSize" DROP DEFAULT,
ALTER COLUMN "mimeType" DROP DEFAULT,
ALTER COLUMN "updatedAt" DROP DEFAULT;

-- AlterTable
ALTER TABLE "Session" ALTER COLUMN "lastUsedAt" DROP DEFAULT;
