services:
  - type: web
    name: sapphire-platform-server
    env: node
    plan: free
    buildCommand: npm install && npx prisma generate
    startCommand: npx prisma migrate deploy && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    autoDeploy: false
